version: '3.5'
services:
  flaskapidb:
    image: postgres:latest
    container_name: "flaskapidb"
    environment:
      - POSTGRES_PASSWORD=Password123!
      - POSTGRES_USER=flaskdbuser 
      - POSTGRES_DB=flaskapidb
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 5432:5432
  flaskapi:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
networks:
  default:
    name: flaskapinw

 
